export const skills = () => {
  const skills = document.createElement('article');
  skills.classList.add('card', 'three-column');
  skills.innerHTML = `
    <h2>技能与相关属性</h2>
    <div class="tables-wide">
      <table>
        <thead>
          <tr>
            <th>技能</th>
            <th>属性</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>杂技</td>
            <td>敏捷</td>
          </tr>
          <tr>
            <td>驯兽</td>
            <td>敏捷</td>
          </tr>
          <tr>
            <td>奥秘</td>
            <td>智力</td>
          </tr>
          <tr>
            <td>运动</td>
            <td>力量</td>
          </tr>
          <tr>
            <td>欺瞒</td>
            <td>魅力</td>
          </tr>
          <tr>
            <td>历史</td>
            <td>智力</td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th>技能</th>
            <th>属性</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>洞察</td>
            <td>感知</td>
          </tr>
          <tr>
            <td>威吓</td>
            <td>魅力</td>
          </tr>
          <tr>
            <td>调查</td>
            <td>智力</td>
          </tr>
          <tr>
            <td>医疗</td>
            <td>感知</td>
          </tr>
          <tr>
            <td>自然</td>
            <td>智力</td>
          </tr>
          <tr>
            <td>察觉</td>
            <td>感知</td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr>
            <th>技能</th>
            <th>属性</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>表演</td>
            <td>魅力</td>
          </tr>
          <tr>
            <td>说服</td>
            <td>魅力</td>
          </tr>
          <tr>
            <td>宗教</td>
            <td>智力</td>
          </tr>
          <tr>
            <td>巧手</td>
            <td>敏捷</td>
          </tr>
          <tr>
            <td>潜行</td>
            <td>敏捷</td>
          </tr>
          <tr>
            <td>求生</td>
            <td>感知</td>
          </tr>
        </tbody>
      </table>
    </div>
  `;
  return skills;
};